
export const baseProfiles = [
  {
    id: "profile-1",
    name: "Emma",
    age: 28,
    gender: "female",
    location: "San Francisco, CA",
    bio: "Product designer passionate about sustainable living and weekend hiking adventures. Looking for someone who values deep conversations and shares my love for exploring new places.",
    photo: "https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=400&h=400&fit=crop&crop=face",
    religion: "Agnostic",
    politics: "Liberal",
    education: "Bachelor's Degree",
    wantsChildren: "yes",
    lifestyle: ["non-smoker", "social-drinker", "fitness-enthusiast"]
  },
  {
    id: "profile-2", 
    name: "Sarah",
    age: 26,
    gender: "female",
    location: "Berkeley, CA",
    bio: "Environmental scientist who loves rock climbing and cooking experimental dishes. Seeking a partner who's intellectually curious and environmentally conscious.",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    religion: "Spiritual",
    politics: "Liberal",
    education: "Master's Degree",
    wantsChildren: "maybe",
    lifestyle: ["non-smoker", "occasional-drinker", "outdoor-enthusiast"]
  },
  {
    id: "profile-3",
    name: "Alex",
    age: 32,
    gender: "male",
    location: "Palo Alto, CA",
    bio: "Software engineer with a passion for jazz music and artisanal coffee. Looking for someone who appreciates both quiet evenings and spontaneous city explorations.",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    religion: "Atheist",
    politics: "Moderate",
    education: "Master's Degree",
    wantsChildren: "yes",
    lifestyle: ["non-smoker", "coffee-enthusiast", "music-lover"]
  },
  {
    id: "profile-4",
    name: "Maya",
    age: 29,
    gender: "female", 
    location: "Oakland, CA",
    bio: "Yoga instructor and wellness coach who believes in mindful living. Seeking a genuine connection with someone who values personal growth and emotional intelligence.",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    religion: "Buddhist",
    politics: "Liberal",
    education: "Bachelor's Degree",
    wantsChildren: "maybe",
    lifestyle: ["non-smoker", "non-drinker", "yoga-practitioner"]
  },
  {
    id: "profile-5",
    name: "David",
    age: 31,
    gender: "male",
    location: "San Jose, CA",
    bio: "Marketing manager who loves weekend farmers markets and trying new restaurants. Looking for someone who shares my appreciation for good food and meaningful conversations.",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    religion: "Christian",
    politics: "Moderate",
    education: "Bachelor's Degree", 
    wantsChildren: "yes",
    lifestyle: ["non-smoker", "social-drinker", "foodie"]
  },
  {
    id: "profile-6",
    name: "Lisa",
    age: 27,
    gender: "female",
    location: "Mountain View, CA", 
    bio: "Graphic designer with a love for vintage books and indie films. Seeking someone who appreciates creativity and isn't afraid to be authentically themselves.",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    religion: "Agnostic",
    politics: "Liberal",
    education: "Bachelor's Degree",
    wantsChildren: "no",
    lifestyle: ["non-smoker", "occasional-drinker", "art-lover"]
  },
  {
    id: "profile-7",
    name: "Michael",
    age: 30,
    gender: "male",
    location: "Redwood City, CA",
    bio: "Financial analyst who enjoys weekend cycling and cooking elaborate meals. Looking for a partner who values both adventure and cozy nights in.",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    religion: "Catholic",
    politics: "Conservative",
    education: "Master's Degree",
    wantsChildren: "yes", 
    lifestyle: ["non-smoker", "wine-enthusiast", "cycling-enthusiast"]
  },
  {
    id: "profile-8",
    name: "Jessica",
    age: 25,
    gender: "female",
    location: "Sunnyvale, CA",
    bio: "Elementary school teacher who loves board games and weekend camping trips. Seeking someone kind-hearted who shares my love for learning and outdoor adventures.",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
    religion: "Christian",
    politics: "Moderate",
    education: "Bachelor's Degree",
    wantsChildren: "yes",
    lifestyle: ["non-smoker", "occasional-drinker", "outdoor-enthusiast"]
  }
];
