
export const baseProfiles = [
  {
    id: "emma_001",
    name: "Emma",
    age: 28,
    gender: "women", // This should match the preference values
    location: "Downtown • 2 miles away",
    bio: "Art curator who believes in deep connections and meaningful conversations. Looking for someone to explore galleries and life with.",
    photo: "https://images.unsplash.com/photo-1494790108755-2616b612b190?w=150&h=150&fit=crop&crop=face",
    wantsChildren: true,
    education: "masters",
    religion: "spiritual",
    politics: "liberal",
    careerAmbition: "high",
    lifestyle: ["fitness", "arts", "travel"]
  },
  {
    id: "sarah_002",
    name: "Sarah",
    age: 26,
    gender: "women",
    location: "Midtown • 3 miles away",
    bio: "Therapist passionate about personal growth and authentic relationships. Loves hiking, reading, and cozy coffee dates.",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    wantsChildren: "maybe",
    education: "masters",
    religion: "agnostic",
    politics: "moderate",
    careerAmbition: "moderate",
    lifestyle: ["outdoor", "wellness", "reading"]
  },
  {
    id: "maya_003",
    name: "Maya",
    age: 30,
    gender: "women",
    location: "Uptown • 1 mile away",
    bio: "Software engineer with a love for travel and learning new cultures. Seeking a partner for life's adventures.",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    wantsChildren: true,
    education: "bachelors",
    religion: "none",
    politics: "liberal",
    careerAmbition: "high",
    lifestyle: ["tech", "travel", "food"]
  },
  {
    id: "zoe_004",
    name: "Zoe",
    age: 29,
    gender: "women",
    location: "Westside • 4 miles away",
    bio: "Veterinarian who adores animals and nature. Looking for someone who shares my values of compassion and family.",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face",
    wantsChildren: true,
    education: "doctorate",
    religion: "christian",
    politics: "moderate",
    careerAmbition: "moderate",
    lifestyle: ["animals", "nature", "family"]
  },
  {
    id: "lily_005",
    name: "Lily",
    age: 27,
    gender: "women",
    location: "East End • 2 miles away",
    bio: "Teacher and aspiring writer who believes in the power of stories. Ready to write our next chapter together.",
    photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&h=150&fit=crop&crop=face",
    wantsChildren: false,
    education: "masters",
    religion: "spiritual",
    politics: "liberal",
    careerAmbition: "moderate",
    lifestyle: ["writing", "education", "arts"]
  },
  // Adding some male profiles for testing
  {
    id: "alex_006",
    name: "Alex",
    age: 32,
    gender: "men",
    location: "Downtown • 1 mile away",
    bio: "Architect passionate about sustainable design and urban planning. Looking for someone who shares my vision for a better world.",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    wantsChildren: true,
    education: "masters",
    religion: "agnostic",
    politics: "liberal",
    careerAmbition: "high",
    lifestyle: ["design", "sustainability", "travel"]
  },
  {
    id: "james_007",
    name: "James",
    age: 29,
    gender: "men",
    location: "Midtown • 2 miles away",
    bio: "Marketing professional who loves cooking and exploring new restaurants. Seeking a partner to share culinary adventures with.",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    wantsChildren: "maybe",
    education: "bachelors",
    religion: "none",
    politics: "moderate",
    careerAmbition: "moderate",
    lifestyle: ["food", "cooking", "social"]
  },
  {
    id: "david_008",
    name: "David",
    age: 31,
    gender: "men",
    location: "Uptown • 3 miles away",
    bio: "Doctor committed to helping others and building meaningful relationships. Looking for a life partner to share in service and love.",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    wantsChildren: true,
    education: "doctorate",
    religion: "christian",
    politics: "moderate",
    careerAmbition: "high",
    lifestyle: ["healthcare", "family", "service"]
  }
];
