
export const baseProfiles = [
  {
    id: "emma_profile",
    name: "Emma",
    age: 28,
    gender: "female", // Added gender field
    location: "San Francisco, CA",
    bio: "Adventure seeker and coffee enthusiast. Love hiking, reading, and trying new restaurants. Looking for someone to explore life with!",
    photo: "https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=400&h=400&fit=crop&crop=face",
    education: "bachelor",
    careerAmbition: "balanced",
    religion: "spiritual",
    politics: "moderate",
    lifestyle: ["fitness", "travel"],
    wantsChildren: "yes"
  },
  {
    id: "sarah_profile", 
    name: "Sarah",
    age: 26,
    gender: "female",
    location: "Los Angeles, CA",
    bio: "Artist and yoga instructor. Passionate about creativity, mindfulness, and making a positive impact. Seeking deep connection.",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    education: "bachelor",
    careerAmbition: "creative",
    religion: "buddhist",
    politics: "liberal",
    lifestyle: ["yoga", "art"],
    wantsChildren: "maybe"
  },
  {
    id: "maya_profile",
    name: "Maya", 
    age: 31,
    gender: "female",
    location: "Seattle, WA",
    bio: "Tech professional with a love for the outdoors. Enjoy rock climbing, board games, and good conversations over wine.",
    photo: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face",
    education: "master",
    careerAmbition: "ambitious",
    religion: "agnostic",
    politics: "liberal",
    lifestyle: ["outdoors", "tech"],
    wantsChildren: "yes"
  },
  {
    id: "zoe_profile",
    name: "Zoe",
    age: 24,
    gender: "female", 
    location: "Austin, TX",
    bio: "Music lover and food blogger. Always discovering new bands and restaurants. Looking for someone to share adventures with!",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
    education: "bachelor",
    careerAmbition: "creative",
    religion: "none",
    politics: "moderate",
    lifestyle: ["music", "food"],
    wantsChildren: "maybe"
  },
  {
    id: "lily_profile",
    name: "Lily",
    age: 29,
    gender: "female",
    location: "Portland, OR", 
    bio: "Environmental scientist and weekend warrior. Love camping, sustainable living, and meaningful conversations about the future.",
    photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=face",
    education: "phd",
    careerAmbition: "mission_driven",
    religion: "spiritual",
    politics: "liberal",
    lifestyle: ["environment", "outdoors"],
    wantsChildren: "yes"
  },
  // Male profiles for users seeking men
  {
    id: "alex_profile",
    name: "Alex",
    age: 30,
    gender: "male",
    location: "Denver, CO",
    bio: "Software engineer who loves the mountains. Passionate about skiing, craft beer, and building things that matter.",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    education: "bachelor",
    careerAmbition: "balanced",
    religion: "agnostic", 
    politics: "moderate",
    lifestyle: ["outdoors", "tech"],
    wantsChildren: "yes"
  },
  {
    id: "james_profile",
    name: "James",
    age: 32,
    gender: "male",
    location: "Chicago, IL",
    bio: "Marketing director and weekend chef. Love exploring the city's food scene and hosting dinner parties for friends.",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    education: "master",
    careerAmbition: "ambitious",
    religion: "christian",
    politics: "moderate",
    lifestyle: ["food", "social"],
    wantsChildren: "yes"
  },
  {
    id: "david_profile", 
    name: "David",
    age: 27,
    gender: "male",
    location: "Boston, MA",
    bio: "Doctor and avid reader. Passionate about helping others and lifelong learning. Seeking someone who values growth and compassion.",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    education: "phd",
    careerAmbition: "mission_driven",
    religion: "spiritual",
    politics: "liberal", 
    lifestyle: ["books", "fitness"],
    wantsChildren: "yes"
  }
];
