// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyvkqbgujqtcztmnjjmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dmtxYmd1anF0Y3p0bW5qam12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTUwMTksImV4cCI6MjA2NTU3MTAxOX0.TqNMYbxaEXM-fTjcaEwTWTkWz1uuAtpgtK7Ee6MqIL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);